In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('/content/cars.csv')
df.head()

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,?,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,?,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   body-style         205 non-null    object
 5   drive-wheels       205 non-null    object
 6   engine-location    205 non-null    object
 7   width              205 non-null    float64
 8   height             205 non-null    float64
 9   engine-type        205 non-null    object
 10  engine-size        205 non-null    int64
 11  horsepower         205 non-null    object
 12  city-mpg           205 non-null    int64
 13  highway-mpg        205 non-null    int64
 14  price              205 non-null    int64
dtypes: float64(2), int64(5), object(8)
memory usage: 24.1+ KB

In [6]:
df.replace('?', np.nan, inplace =True)

In [7]:
df.head()

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,13495
1,3,NaN,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111,21,27,16500
2,1,NaN,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154,19,26,16500
3,2,164,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102,24,30,13950
4,2,164,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115,18,22,17450

In [8]:
df.isna().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
body-style            0
drive-wheels          0
engine-location       0
width                 0
height                0
engine-type           0
engine-size           0
horsepower            2
city-mpg              0
highway-mpg           0
price                 0
dtype: int64

In [9]:
#imputeing nan with mean

from sklearn.impute import SimpleImputer
si = SimpleImputer()

df.loc[:,['normalized-losses', 'horsepower']] = si.fit_transform(df.loc[:,['normalized-losses', 'horsepower']])
df.head()

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,122.0,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111.0,21,27,13495
1,3,122.0,alfa-romero,gas,convertible,rwd,front,64.1,48.8,dohc,130,111.0,21,27,16500
2,1,122.0,alfa-romero,gas,hatchback,rwd,front,65.5,52.4,ohcv,152,154.0,19,26,16500
3,2,164.0,audi,gas,sedan,fwd,front,66.2,54.3,ohc,109,102.0,24,30,13950
4,2,164.0,audi,gas,sedan,4wd,front,66.4,54.3,ohc,136,115.0,18,22,17450

In [10]:
#Applying Ordinal encoding on all the categorical columns

from sklearn.preprocessing import OrdinalEncoder
oe = OrdinalEncoder()

In [11]:
#Selecting Categorical Columns

cat_cols = df.select_dtypes(object).columns
cat_cols

Index(['make', 'fuel-type', 'body-style', 'drive-wheels', 'engine-location',
       'engine-type'],
      dtype='object')

In [12]:
df[cat_cols] = oe.fit_transform (df[cat_cols])
df.head()

,symboling,normalized-losses,make,fuel-type,body-style,drive-wheels,engine-location,width,height,engine-type,engine-size,horsepower,city-mpg,highway-mpg,price
0,3,122.0,0.0,1.0,0.0,2.0,0.0,64.1,48.8,0.0,130,111.0,21,27,13495
1,3,122.0,0.0,1.0,0.0,2.0,0.0,64.1,48.8,0.0,130,111.0,21,27,16500
2,1,122.0,0.0,1.0,2.0,2.0,0.0,65.5,52.4,5.0,152,154.0,19,26,16500
3,2,164.0,1.0,1.0,3.0,1.0,0.0,66.2,54.3,3.0,109,102.0,24,30,13950
4,2,164.0,1.0,1.0,3.0,0.0,0.0,66.4,54.3,3.0,136,115.0,18,22,17450

**Feature Scaling**

In [13]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge

In [14]:
X = df.iloc[:,:-1]
Y = df.iloc[:,-1]

In [16]:
sc = StandardScaler()
X = sc.fit_transform(X)

In [17]:
xtrain,xtest,ytrain,ytest = train_test_split(X,Y,test_size =0.2,random_state=1)

**Linear Regression**

In [19]:
lr = LinearRegression()
lr.fit(xtrain,ytrain)
ypred = lr.predict(xtest)

print (f"Training accuracy :", lr.score(xtrain,ytrain))
print (f"Testing accuracy :", lr.score(xtest,ytest))

Training accuracy : 0.8539412613914049
Testing accuracy : 0.7440263258545714

In [20]:
lr.coef_

array([  100.70152137,  -157.4653771 , -1212.01831145,  -117.77994561,
        -136.52459077,  1128.78608008,  1941.04219971,  1738.41814208,
         698.58953363,   320.35950293,  4041.59046649,  -492.16608863,
        1553.21174218, -2450.66724917])

**Ridge Regression**

In [24]:
rg = Ridge()
rg.fit(xtrain,ytrain)
rgpred = rg.predict(xtest)

print (f"Training accuracy :", rg.score(xtrain,ytrain))
print (f"Testing accuracy :", rg.score(xtest,ytest))

Training accuracy : 0.853793795232896
Testing accuracy : 0.7468034822961305

In [25]:
rg.coef_

array([   75.92706967,  -158.17628146, -1206.42216987,  -162.04093081,
        -156.48856711,  1121.67903706,  1905.61194134,  1719.20463905,
         713.53938244,   328.91482672,  3990.47650541,  -442.90460517,
        1164.75979456, -2082.05211597])

**Lasso Regression**

In [26]:
ls = Lasso()
ls.fit(xtrain,ytrain)
lspred = ls.predict(xtest)

print (f"Training accuracy :", ls.score(xtrain,ytrain))
print (f"Testing accuracy :", ls.score(xtest,ytest))

Training accuracy : 0.8539397391560521
Testing accuracy : 0.7443240787367613

In [27]:
ls.coef_

array([   96.09444864,  -155.11949836, -1210.42544506,  -121.19910051,
        -136.9606948 ,  1125.95047422,  1938.2903356 ,  1735.22990129,
         698.10371721,   319.73213183,  4041.72530326,  -489.85761144,
        1512.68920683, -2412.56609442])

**Selection of alpha**

In [43]:
for i in range(2500,2550):
  rg = Ridge(alpha =i)
  rg.fit(xtrain,ytrain)
  y = rgpred = rg.predict(xtest)
  print(f"{i} {rg.score(xtrain,ytrain)} {rg.score(xtest,ytest)}")

2500 0.30150050236557635 0.2687639890612853
2501 0.3014181734623109 0.26868236580036575
2502 0.3013358888549096 0.26860078612983773
2503 0.3012536485082925 0.2685192500155653
2504 0.30117145238741627 0.2684377574234468
2505 0.30108930045727345 0.2683563083194157
2506 0.30100719268289244 0.26827490266943954
2507 0.30092512902933777 0.2681935404395205
2508 0.3008431094617101 0.2681122215956946
2509 0.3007611339451456 0.2680309461040328
2510 0.30067920244481683 0.26794971393064027
2511 0.3005973149259318 0.26786852504165615
2512 0.30051547135373435 0.26778737940325426
2513 0.3004336716935041 0.2677062769816423
2514 0.30035191591055654 0.2676252177430619
2515 0.3002702039702423 0.2675442016537892
2516 0.30018853583794813 0.26746322868013417
2517 0.3001069114790962 0.267382298788441
2518 0.30002533085914385 0.2673014119450875
2519 0.2999437939435844 0.26722056811648576
2520 0.29986230069794617 0.2671397672690814
2521 0.2997808510877932 0.26705900936935434
2522 0.2996994450787246 0.26697829438381815
2523 0.2996180826363748 0.2668976222790196
2524 0.2995367637264138 0.26681699302154016
2525 0.2994554883145465 0.2667364065779946
2526 0.2993742563665127 0.26665586291503085
2527 0.29929306784808807 0.26657536199933085
2528 0.2992119227250827 0.2664949037976103
2529 0.29913082096334165 0.2664144882766183
2530 0.2990497625287457 0.26633411540313723
2531 0.29896874738721 0.2662537851439831
2532 0.29888777550468426 0.26617349746600505
2533 0.2988068468471542 0.26609325233608605
2534 0.2987259613806391 0.26601304972114204
2535 0.29864511907119384 0.26593288958812245
2536 0.2985643198849076 0.2658527719040097
2537 0.2984835637879045 0.2657726966358198
2538 0.2984028507463431 0.2656926637506014
2539 0.2983221807264167 0.2656126732154366
2540 0.2982415536943529 0.26553272499744085
2541 0.29816096961641436 0.26545281906376206
2542 0.2980804284588977 0.26537295538158134
2543 0.2979999301881341 0.26529313391811327
2544 0.29791947477048897 0.26521335464060436
2545 0.29783906217236256 0.26513361751633513
2546 0.29775869236018904 0.26505392251261817
2547 0.2976783653004367 0.26497426959679893
2548 0.2975980809596084 0.2648946587362563
2549 0.29751783930424125 0.26481508989840086

In [44]:
for i in range(1500,1600):
  ls = Lasso(alpha =i)
  ls.fit(xtrain,ytrain)
  y = rgpred = ls.predict(xtest)
  print(f"{i} {ls.score(xtrain,ytrain)} {ls.score(xtest,ytest)}")

1500 0.7472950532074247 0.6828774456383304
1501 0.7471946197757003 0.6828079737359083
1502 0.7470941194145466 0.6827384503667657
1503 0.7469935521239637 0.682668875530903
1504 0.7468929179039512 0.6825992492283199
1505 0.7467922167545095 0.6825295714590164
1506 0.7466914486756384 0.6824598422229925
1507 0.7465906136673381 0.6823900615202483
1508 0.7464897117296085 0.6823202293507837
1509 0.7463887428624496 0.6822503457145987
1510 0.7462877070658612 0.6821804106116934
1511 0.7461866043398437 0.6821104240420678
1512 0.7460854346843968 0.6820403860057218
1513 0.7459841980995205 0.6819702965026553
1514 0.745882894585215 0.6819001555328685
1515 0.7457815241414802 0.6818299630963616
1516 0.745680086768316 0.681759719193134
1517 0.7455785824657225 0.6816894238231862
1518 0.7454770112336996 0.6816190769865181
1519 0.7453753730722475 0.6815486786831295
1520 0.7452736679813661 0.6814782289130206
1521 0.7451718959610553 0.6814077276761913
1522 0.7450700570113152 0.6813371749726416
1523 0.7449681511321458 0.6812665708023716
1524 0.7448661783235471 0.6811959151653812
1525 0.744764138585519 0.6811252080616705
1526 0.7446620319180617 0.6810544494912394
1527 0.7445598583211752 0.6809836394540882
1528 0.7444576177948591 0.6809127779502162
1529 0.7443553103391138 0.6808418649796242
1530 0.7442529359539393 0.6807709005423117
1531 0.7441504946393354 0.6806998846382788
1532 0.744047986395302 0.6806288172675256
1533 0.7439454112218394 0.6805576984300519
1534 0.7438427691189475 0.6804865281258579
1535 0.7437400600866264 0.6804153063549436
1536 0.743637284124876 0.680344033117309
1537 0.743534441233696 0.6802727084129538
1538 0.7434315314130868 0.6802013322418785
1539 0.7433285546630484 0.6801299046040827
1540 0.7432255109835807 0.6800584254995666
1541 0.7431224003746837 0.6799868949283301
1542 0.7430192228363571 0.6799153128903733
1543 0.7429159783686015 0.6798436793856961
1544 0.7428126669714163 0.6797719944142986
1545 0.742709288644802 0.6797002579761806
1546 0.7426058433887583 0.6796284700713424
1547 0.7425023312032855 0.6795566306997838
1548 0.742398752088383 0.6794847398615047
1549 0.7422951060440515 0.6794127975565054
1550 0.7421913930702904 0.6793408037847857
1551 0.7420876131671001 0.6792687585463455
1552 0.7419837663344806 0.6791966618411851
1553 0.7418798525724317 0.6791245136693043
1554 0.7417758718809535 0.6790523140307031
1555 0.741671824260046 0.6789800629253816
1556 0.7415677097097091 0.6789077603533398
1557 0.741463528229943 0.6788354063145775
1558 0.7413592798207476 0.6787630008090948
1559 0.7412549644821227 0.6786905438368919
1560 0.7411505822140687 0.6786180353979686
1561 0.7410461330165852 0.6785454754923249
1562 0.7409416168896723 0.6784728641199609
1563 0.7408370338333303 0.6784002012808765
1564 0.7407323838475589 0.6783274869750717
1565 0.7406276669323583 0.6782547212025467
1566 0.7405228830877283 0.678181903963301
1567 0.7404180323136689 0.6781090352573352
1568 0.7403131146101802 0.678036115084649
1569 0.7402081299772624 0.6779631434452424
1570 0.7401030784149152 0.6778901203391154
1571 0.7399979599231385 0.6778170457662682
1572 0.7398927745019325 0.6777439197267006
1573 0.7397875221512973 0.6776707422204126
1574 0.7396822028712328 0.6775975132474044
1575 0.7395768166617389 0.6775242328076755
1576 0.7394713635228157 0.6774509009012264
1577 0.7393658434544632 0.677377517528057
1578 0.7392602564566814 0.6773040826881672
1579 0.7391546025294703 0.677230596381557
1580 0.7390488816728298 0.6771570586082265
1581 0.73894309388676 0.6770834693681755
1582 0.738837239171261 0.6770098286614044
1583 0.7387313175263325 0.6769361364879127
1584 0.7386253289519749 0.6768623928477008
1585 0.7385192734481878 0.6767885977407684
1586 0.7384131510149714 0.6767147511671157
1587 0.7383069616523258 0.6766408531267426
1588 0.7382007053602508 0.6765669036196492
1589 0.7380943821387465 0.6764929026458355
1590 0.7379879919878128 0.6764188502053012
1591 0.7378815349074501 0.676344746298047
1592 0.7377750108976577 0.676270590924072
1593 0.7376684199584362 0.6761963840833768
1594 0.7375617620897853 0.6761221257759611
1595 0.737455037291705 0.6760478160018251
1596 0.7373482455641956 0.675973454760969
1597 0.7372413869072567 0.6758990420533924
1598 0.7371344613208886 0.6758245778790952
1599 0.7370274688050912 0.6757500622380779